# Generated by Django 3.0.6 on 2020-05-23 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200523_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='project_year',
        ),
        migrations.AddField(
            model_name='job',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
