# Generated by Django 3.0.6 on 2020-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200524_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
