# Generated by Django 3.0.6 on 2020-05-22 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 13, 36, 26, 567010))),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
